site_name: Sendanor.com
site_url: https://www.sendanor.com/
site_author: Sendanor
remote_branch: master
docs_dir: src
site_dir: docs
copyright: Copyright (c) 2007-2021 <a href="mailto:info@sendanor.com">Sendanor</a>, FI-20925406
nav:
- 'About': 'index.md'
- Software:
  - 'Our software': 'software.md'
  - 'Forms':
      - 'Getting Started with Forms': 'forms/index.md'
      - 'Setting up a form': 'forms/creating-form.md'
      - 'Editing a form': 'forms/editing-form.md'
      - 'Configuring a pipeline': 'forms/configuring-pipeline.md'
      - 'Examples':
        - 'Commenting on static webpage': 'forms/examples/commenting-on-blog.md'
  - 'Pipelines':
      - 'Getting Started with Pipelines': 'pipelines/index.md'
      - 'Pipeline Agents': 'pipelines/agent/index.md'
      - 'Pipeline Runner': 'pipelines/runner/index.md'
      - 'Pipeline Models':
        - 'Getting started with models':  'pipelines/model/index.md'
        - 'Common properties':  'pipelines/model/common-properties.md'
        - 'Naming rules':  'pipelines/model/naming-rules.md'
        - 'Pipeline': 'pipelines/model/pipeline.md'
        - 'Stage': 'pipelines/model/stage.md'
        - 'Job': 'pipelines/model/job.md'
        - 'Steps':
          - 'Getting started with steps': 'pipelines/model/step/index.md'
          - 'Command': 'pipelines/model/step/command.md'
          - 'Git': 'pipelines/model/step/git.md'
          - 'File': 'pipelines/model/step/file.md'
          - 'Json': 'pipelines/model/step/json.md'
          - 'Csv': 'pipelines/model/step/csv.md'
          - 'Assert': 'pipelines/model/step/assert.md'
          - 'Concat': 'pipelines/model/step/concat.md'
          - 'Variable': 'pipelines/model/step/variable.md'
        - 'Parameters':  'pipelines/model/parameters.md'
        - 'Variables':  'pipelines/model/variables.md'
  - 'Chat':
    - 'Getting Started with Chat': 'chat/index.md'
  - 'Live':
    - 'Getting Started with Live': 'live/index.md'
  - Roadmap: 'roadmap.md'
- 'Contact Us': 'support.md'
theme:
  custom_dir: overrides
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
    primary: black
    accent: light blue
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
    primary: black
    accent: cyan
  favicon: img/favicon.ico
  logo: assets/sendanor.svg
  name: material
  language: en
  highlightjs: true
  features:
  - navigation.instant
  - navigation.tracking
  - navigation.tabs
  - navigation.top
  - toc.integrate
plugins:
- search:
    min_search_length: 2
    indexing: 'full'
extra_css:
- stylesheets/extra.css
markdown_extensions:
- meta
- attr_list
- pymdownx.tabbed
- pymdownx.superfences
- toc:
    permalink: true
    slugify: !!python/name:pymdownx.slugs.uslugify
extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/sendanor
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/company/sendanor/
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/sendanorcom
  - icon: fontawesome/brands/discord
    link: https://discord.gg/dVTpkTh
  - icon: fontawesome/brands/facebook
    link: https://www.facebook.com/sendanor/
  analytics:
    provider: google
    property: UA-22467175-1
  alternate:
  - name: Finnish
    link: https://www.sendanor.fi/
    lang: fi
